#############################################################################
# Makefile for building: ProjetIHM
# Generated by qmake (2.01a) (Qt 4.8.4) on: jeu. mai 1 17:21:01 2014
# Project:  ProjetIHM.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ProjetIHM.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtDeclarative -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		headband.cpp \
		label_select.cpp \
		headbandscrollarea.cpp \
		headband_item.cpp \
		scrollareawidget.cpp \
		etiquette.cpp \
		MealModel.cpp \
		languette.cpp \
		languetteContainer.cpp \
		headbandfactory.cpp \
		headband_menu.cpp \
		headband_meal.cpp moc_mainwindow.cpp \
		moc_headband.cpp \
		moc_arrow.cpp \
		moc_headbandscrollarea.cpp \
		moc_headband_item.cpp \
		moc_scrollareawidget.cpp \
		moc_etiquette.cpp \
		moc_MealModel.cpp \
		moc_languetteContainer.cpp \
		moc_headband_menu.cpp \
		moc_headband_meal.cpp \
		qrc_Ressources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		headband.o \
		label_select.o \
		headbandscrollarea.o \
		headband_item.o \
		scrollareawidget.o \
		etiquette.o \
		MealModel.o \
		languette.o \
		languetteContainer.o \
		headbandfactory.o \
		headband_menu.o \
		headband_meal.o \
		moc_mainwindow.o \
		moc_headband.o \
		moc_arrow.o \
		moc_headbandscrollarea.o \
		moc_headband_item.o \
		moc_scrollareawidget.o \
		moc_etiquette.o \
		moc_MealModel.o \
		moc_languetteContainer.o \
		moc_headband_menu.o \
		moc_headband_meal.o \
		qrc_Ressources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ProjetIHM.pro
QMAKE_TARGET  = ProjetIHM
DESTDIR       = 
TARGET        = ProjetIHM

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ProjetIHM.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtDeclarative.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ProjetIHM.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtDeclarative.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ProjetIHM.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ProjetIHM1.0.0 || $(MKDIR) .tmp/ProjetIHM1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ProjetIHM1.0.0/ && $(COPY_FILE) --parents mainwindow.h headband.h arrow.h label_select.h headbandscrollarea.h headband_item.h scrollareawidget.h languette.h etiquette.h MealModel.h languette.h languetteContainer.h headbandfactory.h headband_menu.h headband_meal.h .tmp/ProjetIHM1.0.0/ && $(COPY_FILE) --parents Ressources.qrc .tmp/ProjetIHM1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp headband.cpp label_select.cpp headbandscrollarea.cpp headband_item.cpp scrollareawidget.cpp etiquette.cpp MealModel.cpp languette.cpp languetteContainer.cpp headbandfactory.cpp headband_menu.cpp headband_meal.cpp .tmp/ProjetIHM1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/ProjetIHM1.0.0/ && (cd `dirname .tmp/ProjetIHM1.0.0` && $(TAR) ProjetIHM1.0.0.tar ProjetIHM1.0.0 && $(COMPRESS) ProjetIHM1.0.0.tar) && $(MOVE) `dirname .tmp/ProjetIHM1.0.0`/ProjetIHM1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ProjetIHM1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_headband.cpp moc_arrow.cpp moc_headbandscrollarea.cpp moc_headband_item.cpp moc_scrollareawidget.cpp moc_etiquette.cpp moc_MealModel.cpp moc_languetteContainer.cpp moc_headband_menu.cpp moc_headband_meal.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_headband.cpp moc_arrow.cpp moc_headbandscrollarea.cpp moc_headband_item.cpp moc_scrollareawidget.cpp moc_etiquette.cpp moc_MealModel.cpp moc_languetteContainer.cpp moc_headband_menu.cpp moc_headband_meal.cpp
moc_mainwindow.cpp: headband.h \
		arrow.h \
		scrollareawidget.h \
		headband_item.h \
		label_select.h \
		headbandscrollarea.h \
		headband_meal.h \
		headband_menu.h \
		etiquette.h \
		languetteContainer.h \
		MealModel.h \
		languette.h \
		headbandfactory.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_headband.cpp: arrow.h \
		scrollareawidget.h \
		headband_item.h \
		label_select.h \
		headbandscrollarea.h \
		headband_meal.h \
		headband_menu.h \
		headband.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) headband.h -o moc_headband.cpp

moc_arrow.cpp: arrow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) arrow.h -o moc_arrow.cpp

moc_headbandscrollarea.cpp: headbandscrollarea.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) headbandscrollarea.h -o moc_headbandscrollarea.cpp

moc_headband_item.cpp: label_select.h \
		headband_item.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) headband_item.h -o moc_headband_item.cpp

moc_scrollareawidget.cpp: headband_item.h \
		label_select.h \
		scrollareawidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) scrollareawidget.h -o moc_scrollareawidget.cpp

moc_etiquette.cpp: etiquette.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) etiquette.h -o moc_etiquette.cpp

moc_MealModel.cpp: MealModel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) MealModel.h -o moc_MealModel.cpp

moc_languetteContainer.cpp: MealModel.h \
		languette.h \
		languetteContainer.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) languetteContainer.h -o moc_languetteContainer.cpp

moc_headband_menu.cpp: label_select.h \
		headband_item.h \
		headband_menu.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) headband_menu.h -o moc_headband_menu.cpp

moc_headband_meal.cpp: label_select.h \
		headband_item.h \
		headband_meal.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) headband_meal.h -o moc_headband_meal.cpp

compiler_rcc_make_all: qrc_Ressources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Ressources.cpp
qrc_Ressources.cpp: Ressources.qrc \
		menus/Menu1.txt \
		menus/Menu2.txt \
		images/Banner.png \
		images/arrowR.png \
		images/Confirm.jpg \
		images/NumTable.png \
		images/eau.png \
		images/LanguetteDown.png \
		images/arrowL.png \
		images/Serveur.png \
		images/Pain.png \
		images/LangeutteUp.png \
		plats/Creme-Brulee.jpg \
		plats/salade_nicoise.jpg \
		plats/spaghetti.txt \
		plats/boeuf-bourguignon.jpg \
		plats/spaghetti.jpg \
		plats/Tartelette_Citron.jpg \
		plats/tarte_citron.txt \
		plats/boeuf_bourguignon.txt \
		plats/creme_brulee.txt \
		plats/salade_nicoise.txt
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name Ressources Ressources.qrc -o qrc_Ressources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		headband.h \
		arrow.h \
		scrollareawidget.h \
		headband_item.h \
		label_select.h \
		headbandscrollarea.h \
		headband_meal.h \
		headband_menu.h \
		etiquette.h \
		languetteContainer.h \
		MealModel.h \
		languette.h \
		headbandfactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		headband.h \
		arrow.h \
		scrollareawidget.h \
		headband_item.h \
		label_select.h \
		headbandscrollarea.h \
		headband_meal.h \
		headband_menu.h \
		etiquette.h \
		languetteContainer.h \
		MealModel.h \
		languette.h \
		headbandfactory.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

headband.o: headband.cpp headband.h \
		arrow.h \
		scrollareawidget.h \
		headband_item.h \
		label_select.h \
		headbandscrollarea.h \
		headband_meal.h \
		headband_menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headband.o headband.cpp

label_select.o: label_select.cpp label_select.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o label_select.o label_select.cpp

headbandscrollarea.o: headbandscrollarea.cpp headbandscrollarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headbandscrollarea.o headbandscrollarea.cpp

headband_item.o: headband_item.cpp headband_item.h \
		label_select.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headband_item.o headband_item.cpp

scrollareawidget.o: scrollareawidget.cpp scrollareawidget.h \
		headband_item.h \
		label_select.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scrollareawidget.o scrollareawidget.cpp

etiquette.o: etiquette.cpp etiquette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o etiquette.o etiquette.cpp

MealModel.o: MealModel.cpp MealModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MealModel.o MealModel.cpp

languette.o: languette.cpp languette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o languette.o languette.cpp

languetteContainer.o: languetteContainer.cpp languetteContainer.h \
		MealModel.h \
		languette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o languetteContainer.o languetteContainer.cpp

headbandfactory.o: headbandfactory.cpp headbandfactory.h \
		headband.h \
		arrow.h \
		scrollareawidget.h \
		headband_item.h \
		label_select.h \
		headbandscrollarea.h \
		headband_meal.h \
		headband_menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headbandfactory.o headbandfactory.cpp

headband_menu.o: headband_menu.cpp headband_menu.h \
		label_select.h \
		headband_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headband_menu.o headband_menu.cpp

headband_meal.o: headband_meal.cpp headband_meal.h \
		label_select.h \
		headband_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headband_meal.o headband_meal.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_headband.o: moc_headband.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_headband.o moc_headband.cpp

moc_arrow.o: moc_arrow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_arrow.o moc_arrow.cpp

moc_headbandscrollarea.o: moc_headbandscrollarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_headbandscrollarea.o moc_headbandscrollarea.cpp

moc_headband_item.o: moc_headband_item.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_headband_item.o moc_headband_item.cpp

moc_scrollareawidget.o: moc_scrollareawidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scrollareawidget.o moc_scrollareawidget.cpp

moc_etiquette.o: moc_etiquette.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_etiquette.o moc_etiquette.cpp

moc_MealModel.o: moc_MealModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MealModel.o moc_MealModel.cpp

moc_languetteContainer.o: moc_languetteContainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_languetteContainer.o moc_languetteContainer.cpp

moc_headband_menu.o: moc_headband_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_headband_menu.o moc_headband_menu.cpp

moc_headband_meal.o: moc_headband_meal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_headband_meal.o moc_headband_meal.cpp

qrc_Ressources.o: qrc_Ressources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Ressources.o qrc_Ressources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

